name = "tmg-dev"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
kv_namespaces = [
    { binding = "TMGS", id = "56a3f1657a0d4d47b25f837a2477fd84", preview_id = "ff96edd616bf44d19194065815ae2295" }
]
vars = { ENVIRONMENT = "dev" }

[dev]
port = 6661

[env.production]
name = "tmg"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    { binding = "TMGS", id = "56a3f1657a0d4d47b25f837a2477fd84", preview_id = "ff96edd616bf44d19194065815ae2295" }
]
